
get  http://localhost:8000/test

###

get http://localhost:8000/services

###

get http://localhost:8000/services/1


###

post http://localhost:8000/services
Content-Type: application/json

{
 "title" : "Visite guidée avec Manu",
 "description" : "Service gratuit"
}

###

put http://localhost:8000/services/1
Content-Type: application/json

{
    "title": "Petit train touristique 12",
    "description": "Tour du zooparc"
}


###

delete http://localhost:8000/services/9dfdf93d-fcc4-11ee-8026-0242ac140002

###

post http://localhost:8000/images/services
Content-Type: application/json

 {
    "image_url": "./imagetest7.jpg",
    "service_id": "5096717e-fd68-11ee-a19d-0242ac140002"
 }


###


get http://localhost:8000/images/services


###

put http://localhost:8000/images/service/1306c828-00c7-11ef-aaa5-0242ac180002
Content-Type: application/json

{
    "image_url": "/imageupdate3",
    "service_id": "5096717e-fd68-11ee-a19d-0242ac140002"
}


###

get http://localhost:8000/images/45

###

get http://localhost:8000/images/

###

delete http://localhost:8000/images/41698211-05fa-11ef-b1c1-0242ac180002

###

get http://localhost:8000/habitats/

###

get http://localhost:8000/habitats/35

###

post http://localhost:8000/habitats
Content-Type: application/json

{
    "title": "savane",
    "description": "lieu aride et sauvage"
}


###

post http://localhost:8000/habitats/47d4a89a-0604-11ef-b1c1-0242ac180002
Content-Type: application/json

{
    "comment": "deux arbres sont cassés"
}

###

put http://localhost:8000/habitats/532ee94b-02ff-11ef-ae74-0242ac180002
Content-Type: application/json

{
    "title" : "la savane ",
    "description": "lieu aride , sauvage et malgré tout riche en faune"
}

###

delete http://localhost:8000/habitats/532ee94b-02ff-11ef-ae74-0242ac180002


###

get http://localhost:8000/reviews/

###

post http://localhost:8000/reviews/
Content-Type: application/json

{
    "pseudo": "toto",
    "content": "tres bien"
}

###


put http://localhost:8000/reviews/99f7d6dc-03ac-11ef-8c2c-0242ac180002
Content-Type: application/json

{
    "status": false
}

###

get http://localhost:8000/animals

###

post http://localhost:8000/animals
Content-Type: application/json

{
    "firstname": "toto3",
    "habitat": "4ea618eb-05fa-11ef-b1c1-0242ac180002",
    "breed": "037b2b98-0633-11ef-b1c1-0242ac180002"
}

###

post http://localhost:8000/images/animal
Content-Type: application/json

 {
    "image_url": "./imagetest7.jpg",
    "service_id": "5096717e-fd68-11ee-a19d-0242ac140002"
 }

###

get http://localhost:8000/breeds


###


get http://localhost:8000/animals/habitats/4ea618eb-05fa-11ef-b1c1-0242ac180002


###

get http://localhost:8000/veterinaries

###

post http://localhost:8000/veterinaries
Content-Type: application/json

{
    "food":"herbe",
    "grammage": 1700,
    "health":"bon",
    "details_condition":"ras",
    "id_user":"8b9d927f-070a-11ef-bc53-0242ac180002",
    "id_animal":"b3a2ba43-0652-11ef-b1c1-0242ac180002"
}

###

get http://localhost:8000/users

###

put http://localhost:8000/veterinaries/5345c0fa-070b-11ef-bc53-0242ac180002
Content-Type: application/json

{
    "food":"herbe",
    "grammage": 1700,
    "health":"bon",
    "details_condition":"ras",
    "id_user":"8b9d927f-070a-11ef-bc53-0242ac180002",
    "id_animal":"b3a2ba43-0652-11ef-b1c1-0242ac180002"
}

###

get http://localhost:8000/employees/3ec3c8cf-06cd-11ef-bc53-0242ac180002

###

put http://localhost:8000/employees/c654af96-07a7-11ef-93fa-0242ac180002
Content-Type: application/json

 {
    "food":"cuisse de boeuf",
    "grammage":"10000",
    "id_user":"8b9d927f-070a-11ef-bc53-0242ac180002",
    "id_animal":"3ec3c8cf-06cd-11ef-bc53-0242ac180002"
 }


###

 get http://localhost:8000/roles

###

 post http://localhost:8000/users
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2VwYXNib3ZlQGFyY2FkaWEuY29tIiwibmFtZSI6IkFkbWluIiwiaWF0IjoxNzIyNTA1OTQ5LCJleHAiOjE3MjI1MTY3NDl9.rPqPsD4Wjc0szZAAz1DuV7qEubzMEPB0GXqOBR0vHi8

{
    "firstname":"tes",
    "lastname":"test",
    "email":"test@test3.com",
    "password":"veto",
    "id_role":"4df4dee1-1510-11ef-9b15-0654193ea06b"
}


###

post http://localhost:8000/login
Content-Type: application/json

{
    "email":"josepasbove@arcadia.com",
    "password":"Azerty&1"
}

###

get http://localhost:8000/click/Gimli


###

put http://localhost:8000/click/Gimli


###

get http://localhost:8000/click


###

put http://localhost:8000/opening/66350050bc37a8a6882202e1
Content-Type: application/json

{
    "openingTime":"10h00"
}

###

get http://localhost:8000/opening

###

get http://localhost:8000/opening/66350050bc37a8a6882202e1


###

post http://localhost:8000/click
Content-Type: application/json

{
    "firstname":"Boromi",
}

###

post http://localhost:8000/breeds
Content-Type: application/json

{
    "name":"Gorille"
}

###

post http://localhost:8000/send
Content-Type: application/json

{
    "title":"Demande de renseignement",
    "text":"J envoie un mail",
    "emailToResponse":"test@test.com"
}

