
get  http://localhost:8000/test

###

get http://localhost:8000/services

###

get http://localhost:8000/services/1


###

post http://localhost:8000/services
Content-Type: application/json

{
 "title" : "Visite guidée avec Manu",
 "description" : "Service gratuit"
}

###

put http://localhost:8000/services/1
Content-Type: application/json

{
    "title": "Petit train touristique 12",
    "description": "Tour du zooparc"
}


###

delete http://localhost:8000/services/9dfdf93d-fcc4-11ee-8026-0242ac140002

###

post http://localhost:8000/images/services
Content-Type: application/json

 {
    "image_url": "./imagetest7.jpg",
    "service_id": "5096717e-fd68-11ee-a19d-0242ac140002"
 }


###


get http://localhost:8000/images/services


###

put http://localhost:8000/images/service/1306c828-00c7-11ef-aaa5-0242ac180002
Content-Type: application/json

{
    "image_url": "/imageupdate3",
    "service_id": "5096717e-fd68-11ee-a19d-0242ac140002"
}


###

get http://localhost:8000/images/45

###

get http://localhost:8000/images/

###

get http://localhost:8000/habitats/

###

get http://localhost:8000/habitats/35

###

post http://localhost:8000/habitats
Content-Type: application/json

{
    "title": "savane",
    "description": "lieu aride et sauvage"
}


###

post http://localhost:8000/habitats/532ee94b-02ff-11ef-ae74-0242ac180002
Content-Type: application/json

{
    "comment": "un arbre est cassé"
}

###

put http://localhost:8000/habitats/532ee94b-02ff-11ef-ae74-0242ac180002
Content-Type: application/json

{
    "title" : "la savane ",
    "description": "lieu aride , sauvage et malgré tout riche en faune"
}

###

delete http://localhost:8000/habitats/532ee94b-02ff-11ef-ae74-0242ac180002


###

get http://localhost:8000/reviews/

###

post http://localhost:8000/reviews/
Content-Type: application/json

{
    "pseudo": "toto",
    "content": "tres bien"
}

###


put http://localhost:8000/reviews/99f7d6dc-03ac-11ef-8c2c-0242ac180002
Content-Type: application/json

{
    "status": false
}